import type { MTGCard } from '@/lib/types/mtg';

// Lightning Bolt test card with full Scryfall API structure
const lightningBolt: MTGCard = {
  id: "test-lightning-bolt-001",
  oracle_id: "b4eadbb7-de8d-4691-8db8-c1b3fb15ac60",
  name: "Lightning Bolt",
  mana_cost: "{R}",
  cmc: 1,
  type_line: "Instant",
  oracle_text: "Lightning Bolt deals 3 damage to any target.",
  colors: ["R"],
  color_identity: ["R"],
  keywords: [],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "legal",
    gladiator: "legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "legal",
    legacy: "legal",
    pauper: "not_legal",
    vintage: "legal",
    penny: "not_legal",
    commander: "legal",
    oathbreaker: "legal",
    brawl: "not_legal",
    historicbrawl: "legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "legal",
    oldschool: "legal",
    premodern: "legal",
    predh: "legal"
  },
  games: ["paper", "mtgo", "arena"],
  reserved: false,
  foil: true,
  nonfoil: true,
  finishes: ["nonfoil", "foil"],
  oversized: false,
  promo: false,
  reprint: true,
  variation: false,
  set_id: "test-set-id",
  set: "lea",
  set_name: "Limited Edition Alpha",
  set_type: "core",
  set_uri: "https://api.scryfall.com/sets/test-set-id",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Alea&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/lea",
  rulings_uri: "https://api.scryfall.com/cards/test-lightning-bolt-001/rulings",
  prints_search_uri: "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ab4eadbb7-de8d-4691-8db8-c1b3fb15ac60&unique=prints",
  collector_number: "161",
  digital: false,
  rarity: "common",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Christopher Rush",
  artist_ids: ["test-artist-id"],
  illustration_id: "test-illustration-id",
  border_color: "black",
  frame: "1993",
  full_art: false,
  textless: false,
  booster: true,
  story_spotlight: false,
  image_uris: {
    small: "https://cards.scryfall.io/small/front/a/e/ae5f9fb1-5a55-4db3-98a1-2628e3598c18.jpg",
    normal: "https://cards.scryfall.io/normal/front/a/e/ae5f9fb1-5a55-4db3-98a1-2628e3598c18.jpg",
    large: "https://cards.scryfall.io/large/front/a/e/ae5f9fb1-5a55-4db3-98a1-2628e3598c18.jpg",
    png: "https://cards.scryfall.io/png/front/a/e/ae5f9fb1-5a55-4db3-98a1-2628e3598c18.png",
    art_crop: "https://cards.scryfall.io/art_crop/front/a/e/ae5f9fb1-5a55-4db3-98a1-2628e3598c18.jpg",
    border_crop: "https://cards.scryfall.io/border_crop/front/a/e/ae5f9fb1-5a55-4db3-98a1-2628e3598c18.jpg"
  },
  prices: {
    usd: "0.50",
    usd_foil: "2.00",
    eur: "0.40",
    tix: "0.02"
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=209",
    tcgplayer_infinite_articles: "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Lightning+Bolt&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks: "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Lightning+Bolt&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Lightning+Bolt"
  },
  purchase_uris: {
    tcgplayer: "https://www.tcgplayer.com/product/1251?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket: "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Lightning+Bolt&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder: "https://www.cardhoarder.com/cards/23601?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"
  }
};

// Grizzly Bears test card
const grizzlyBears: MTGCard = {
  id: "test-grizzly-bears-001",
  oracle_id: "f2ba9b34-b867-4c32-a3d4-5de1ce984c1c",
  name: "Grizzly Bears",
  mana_cost: "{1}{G}",
  cmc: 2,
  type_line: "Creature — Bear",
  oracle_text: "",
  power: "2",
  toughness: "2",
  colors: ["G"],
  color_identity: ["G"],
  keywords: [],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "legal",
    gladiator: "legal",
    pioneer: "not_legal",
    explorer: "not_legal",
    modern: "legal",
    legacy: "legal",
    pauper: "legal",
    vintage: "legal",
    penny: "legal",
    commander: "legal",
    oathbreaker: "legal",
    brawl: "not_legal",
    historicbrawl: "legal",
    alchemy: "not_legal",
    paupercommander: "legal",
    duel: "legal",
    oldschool: "legal",
    premodern: "legal",
    predh: "legal"
  },
  games: ["paper", "mtgo"],
  reserved: false,
  foil: false,
  nonfoil: true,
  finishes: ["nonfoil"],
  oversized: false,
  promo: false,
  reprint: true,
  variation: false,
  set_id: "test-set-id",
  set: "lea",
  set_name: "Limited Edition Alpha",
  set_type: "core",
  set_uri: "https://api.scryfall.com/sets/test-set-id",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Alea&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/lea",
  rulings_uri: "https://api.scryfall.com/cards/test-grizzly-bears-001/rulings",
  prints_search_uri: "https://api.scryfall.com/cards/search?order=released&q=oracleid%3Af2ba9b34-b867-4c32-a3d4-5de1ce984c1c&unique=prints",
  collector_number: "104",
  digital: false,
  rarity: "common",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Jeff A. Menges",
  artist_ids: ["test-artist-id"],
  illustration_id: "test-illustration-id",
  border_color: "black",
  frame: "1993",
  full_art: false,
  textless: false,
  booster: true,
  story_spotlight: false,
  image_uris: {
    small: "https://cards.scryfall.io/small/front/4/0/409f9b88-f03e-40b6-9883-68c14c37c0de.jpg",
    normal: "https://cards.scryfall.io/normal/front/4/0/409f9b88-f03e-40b6-9883-68c14c37c0de.jpg",
    large: "https://cards.scryfall.io/large/front/4/0/409f9b88-f03e-40b6-9883-68c14c37c0de.jpg",
    png: "https://cards.scryfall.io/png/front/4/0/409f9b88-f03e-40b6-9883-68c14c37c0de.png",
    art_crop: "https://cards.scryfall.io/art_crop/front/4/0/409f9b88-f03e-40b6-9883-68c14c37c0de.jpg",
    border_crop: "https://cards.scryfall.io/border_crop/front/4/0/409f9b88-f03e-40b6-9883-68c14c37c0de.jpg"
  },
  prices: {
    usd: "0.25",
    eur: "0.20",
    tix: "0.01"
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=104",
    tcgplayer_infinite_articles: "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Grizzly+Bears&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks: "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Grizzly+Bears&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Grizzly+Bears"
  },
  purchase_uris: {
    tcgplayer: "https://www.tcgplayer.com/product/1234?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket: "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Grizzly+Bears&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder: "https://www.cardhoarder.com/cards/12345?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"
  }
};

// Serra Angel test card
const serraAngel: MTGCard = {
  id: "test-serra-angel-001",
  oracle_id: "84344b3b-5cc8-4e3d-8cf5-c4f8b5e7e5a7",
  name: "Serra Angel",
  mana_cost: "{3}{W}{W}",
  cmc: 5,
  type_line: "Creature — Angel",
  oracle_text: "Flying, vigilance",
  power: "4",
  toughness: "4",
  colors: ["W"],
  color_identity: ["W"],
  keywords: ["Flying", "Vigilance"],
  legalities: {
    standard: "not_legal",
    future: "not_legal",
    historic: "legal",
    gladiator: "legal",
    pioneer: "legal",
    explorer: "legal",
    modern: "legal",
    legacy: "legal",
    pauper: "not_legal",
    vintage: "legal",
    penny: "not_legal",
    commander: "legal",
    oathbreaker: "legal",
    brawl: "not_legal",
    historicbrawl: "legal",
    alchemy: "not_legal",
    paupercommander: "not_legal",
    duel: "legal",
    oldschool: "legal",
    premodern: "legal",
    predh: "legal"
  },
  games: ["paper", "mtgo", "arena"],
  reserved: false,
  foil: true,
  nonfoil: true,
  finishes: ["nonfoil", "foil"],
  oversized: false,
  promo: false,
  reprint: true,
  variation: false,
  set_id: "test-set-id",
  set: "lea",
  set_name: "Limited Edition Alpha",
  set_type: "core",
  set_uri: "https://api.scryfall.com/sets/test-set-id",
  set_search_uri: "https://api.scryfall.com/cards/search?order=set&q=e%3Alea&unique=prints",
  scryfall_set_uri: "https://scryfall.com/sets/lea",
  rulings_uri: "https://api.scryfall.com/cards/test-serra-angel-001/rulings",
  prints_search_uri: "https://api.scryfall.com/cards/search?order=released&q=oracleid%3A84344b3b-5cc8-4e3d-8cf5-c4f8b5e7e5a7&unique=prints",
  collector_number: "045",
  digital: false,
  rarity: "uncommon",
  card_back_id: "0aeebaf5-8c7d-4636-9e82-8c27447861f7",
  artist: "Douglas Shuler",
  artist_ids: ["test-artist-id"],
  illustration_id: "test-illustration-id",
  border_color: "black",
  frame: "1993",
  full_art: false,
  textless: false,
  booster: true,
  story_spotlight: false,
  image_uris: {
    small: "https://cards.scryfall.io/small/front/9/0/9067f035-de8c-428d-a6c2-262cbd8e8be8.jpg",
    normal: "https://cards.scryfall.io/normal/front/9/0/9067f035-de8c-428d-a6c2-262cbd8e8be8.jpg",
    large: "https://cards.scryfall.io/large/front/9/0/9067f035-de8c-428d-a6c2-262cbd8e8be8.jpg",
    png: "https://cards.scryfall.io/png/front/9/0/9067f035-de8c-428d-a6c2-262cbd8e8be8.png",
    art_crop: "https://cards.scryfall.io/art_crop/front/9/0/9067f035-de8c-428d-a6c2-262cbd8e8be8.jpg",
    border_crop: "https://cards.scryfall.io/border_crop/front/9/0/9067f035-de8c-428d-a6c2-262cbd8e8be8.jpg"
  },
  prices: {
    usd: "1.00",
    usd_foil: "3.50",
    eur: "0.80",
    tix: "0.05"
  },
  related_uris: {
    gatherer: "https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=45",
    tcgplayer_infinite_articles: "https://infinite.tcgplayer.com/search?contentMode=article&game=magic&partner=scryfall&q=Serra+Angel&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    tcgplayer_infinite_decks: "https://infinite.tcgplayer.com/search?contentMode=deck&game=magic&partner=scryfall&q=Serra+Angel&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    edhrec: "https://edhrec.com/route/?cc=Serra+Angel"
  },
  purchase_uris: {
    tcgplayer: "https://www.tcgplayer.com/product/5678?page=1&utm_campaign=affiliate&utm_medium=api&utm_source=scryfall",
    cardmarket: "https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Serra+Angel&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall",
    cardhoarder: "https://www.cardhoarder.com/cards/54321?affiliate_id=scryfall&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall"
  }
};

// Export as array for easy expansion
export const testCards: MTGCard[] = [lightningBolt, grizzlyBears, serraAngel];

export default lightningBolt; // Export default as Lightning Bolt 